### ISSUE TITLE
Syntax error in "evernote/setup.py", line 6

### ISSUE THREAD

**Issue by ronbarak** [cgs/evernote#20]
One of `pypdfocr` pre-requisites is evernote.
When running `pip3 install pypdfocr` I get the following exception:

```
$ pip3 install pypdfocr
...
Collecting evernote (from pypdfocr)
  Using cached evernote-1.25.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/pip-build-9r34fjp5/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'
```

Above is on Cygwin on Windows 7.

**Full traceback:**

```
$ pip3 install pypdfocr
Collecting pypdfocr
  Using cached pypdfocr-0.9.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pillow>=2.2 in /usr/lib/python3.4/site-packages (from pypdfocr)
Collecting reportlab>=2.7 (from pypdfocr)
  Using cached reportlab-3.3.0.tar.gz
Collecting watchdog>=0.6.0 (from pypdfocr)
  Using cached watchdog-0.8.3.tar.gz
Collecting pypdf2>=1.23 (from pypdfocr)
  Using cached PyPDF2-1.26.0.tar.gz
Collecting evernote (from pypdfocr)
  Using cached evernote-1.25.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/pip-build-9r34fjp5/evernote/setup.py", line 6
        exec x
             ^
    SyntaxError: Missing parentheses in call to 'exec'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /cygdrive/c/Users/ADMINI~1/AppData/Local/Temp/pip-build-9r34fjp5/evernote/
```

**Comment by sergiaguilar** [comment]
Did you solve the problem? Because i have the same one...

**Comment by hjanjua** [comment]
have same issue

**Comment by marnanel** [comment]
It falls over because you're trying to install the evernote library under Python 3, but it's written for Python 2.
